kind: pipeline
name: default

steps:
  - name: build
    image: hub.t3s.uk/builder:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
      - name: docker_sock
        path: /run/user/1000/docker.sock
    network_mode: host
    privileged: true
    debug: true
    settings:
      build_type: docker
      release_type: manual
      release_package_master: false
      docker_squash: true
      docker_auth:
        from_secret: hub_auth

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

image_pull_secrets:
  - int_hub_auth
