kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: hub.t3s.uk/builder:latest
    network_mode: host
    privileged: true
    settings:
      build_type: docker
      release_type: manual
      debug: true
      release_package_master: false
      docker_squash: true
      docker_auth:
        from_secret: hub_auth

image_pull_secrets:
  - int_hub_auth
