FROM simplyboo6/vimtur-base@sha256:56ca5d1026ee49d7f197fe735f6817ba8a7687fde1b7c37239bc687046142597

ARG VERSION_NAME=dev

RUN apk add -U g++ make python3

## Copy in source
COPY ./ /app/
RUN echo "$VERSION_NAME" > /app/version

## Build server
RUN cd /app/server && \
    yarn link phash2 && \
    yarn --frozen-lockfile && \
    yarn lint && yarn build

## Build client
RUN cd /app/client && \
    yarn --frozen-lockfile && \
    yarn lint && yarn build:prod && \
    rm -rf node_modules

WORKDIR /app

ENTRYPOINT [ "/sbin/tini", "--", "node", "/app/server/dist/index.js" ]
