FROM simplyboo6/vimtur-base@sha256:07ef3aaabc0c74d665ccfec7f5f39999693a67be1f6d151f15dabccbaa47ae82

ARG VERSION_NAME=dev

RUN apk add -U g++ make python3

## Copy in source
COPY ./ /app/
RUN echo "$VERSION_NAME" > /app/version

## Build server
RUN cd /app/server && \
    yarn link phash2 && \
    yarn --frozen-lockfile && \
    yarn lint && yarn build

## Build client
RUN cd /app/client && \
    yarn --frozen-lockfile && \
    yarn lint && yarn build:prod && \
    rm -rf node_modules

WORKDIR /app

ENTRYPOINT [ "/sbin/tini", "--", "node", "/app/server/dist/index.js" ]
